config/routes.rb
Rails.application.routes.draw do
  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  before_action :set_tweet, only: [:edit, :update, :destroy]

  def index
    @tweets = Tweet.all
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    @tweet = Tweet.new(tweets_params)
    if @tweet.save
       redirect_to tweets_path, notice: "新規投稿しました！"
     else
       render 'new'
    end
  end
  
  def edit

  end
  
  def update

    if @tweet.update(tweets_params)
      redirect_to tweets_path, notice: "投稿をへ編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
 
    @tweet.destroy
    redirect_to tweets_path
  end
  
  private
  
    def tweets_params
      params.require(:tweet).permit(:content)
    end
    
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>

 <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
 <% end %>
 
 <%= link_to "投稿一覧画面に戻る" ,tweets_path %>

app/views/tweets/edit.html.erb
<h2>投稿を編集する</h2>

<%= render 'form' %>

app/views/tweets/index.html.erb
<p><%= notice %></p>

<h1>投稿一覧</h1>

<% @tweets.each do |tweet| %>
  <p>投稿：<%= tweet.content %></p>
  <%= link_to "投稿を編集する", edit_tweet_path(tweet.id) %>
  <%= link_to "投稿を削除する", tweet_path(tweet.id), method: :delete, data: {confirm: '本当に削除していいですか？'} %>
<%  end %>
<br><br>
<%= link_to "新規投稿する", new_tweet_path %>

app/views/tweets/new.html.erb
<h2>新規投稿する</h2>

<%= render 'form' %>